
on:
  push:
    tags:
      - 'v*'  # Trigger on tags that start with 'v'

permissions:
  id-token: write  # Required for OIDC
  contents: read   # Required for checking out the repository

jobs:
  test-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .[test]
          python -m pip install build twine

      - name: Run tests
        run: python -m pytest -v
        # This will stop the workflow if tests fail

      - name: Build package
        run: python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
          packages-dir: dist/
          repository-name: textual-game-of-life
